*----------*
CLOSE DATABASES
*----------*
SELECT 2010
USE OFICINA EXCLUSIVE
PACK 
*----------*
SELECT 2030 
USE OFICINA_BDO EXCLUSIVE
*
COPY TO OFICINA_BDO_TEMP
SELECT 2031 
USE OFICINA_BDO_TEMP EXCLUSIVE
INDEX ON Codofic TAG Codoficx
*----------*
SELECT 3010
USE RESP EXCLUSIVE 
*----------*
SELECT 4010
USE ACTUAL EXCLUSIVE  
*----------*Verifica si Oficina_ANT y Oficina son iguales
SELECT 2010  &&USE OFICINA EXCLUSIVE
GO TOP
DO WHILE !EOF()
   CodoficH=Codofic
   NomoficH=Nomofic
   SELECT 2031  &&USE OFICINA_BDO_TEMP EXCLUSIVE
   ZAP
   APPEND FROM OFICINA_BDO 
   SET ORDER TO 1
   CodoficN=Codofic+1
   *
   SELECT 2030  &&USE OFICINA_BDO EXCLUSIVE
   APPEND BLANK 
   REPLACE Codofic WITH CodoficN
   REPLACE Nomofic WITH NomoficH
   *
   SELECT 3010  &&USE RESP EXCLUSIVE
   REPLACE Codofic WITH CodoficN+500 FOR Codofic=CodoficH
   *
   SELECT 4010  &&USE ACTUAL EXCLUSIVE  
   REPLACE Codofic WITH CodoficN+500 FOR Codofic=CodoficH
   *
   SELECT 2010  &&USE OFICINA EXCLUSIVE
   SKIP 
ENDDO 
*
SELECT 3010  &&USE RESP EXCLUSIVE
REPLACE ALL Codofic WITH Codofic-500
LOCATE FOR Codofic<0
IF FOUND()
   MESSAGEBOX("Oficina Menor a 0",16,"")
   BROWSE
ENDIF 
*
SELECT 4010  &&USE ACTUAL EXCLUSIVE  
REPLACE ALL Codofic WITH Codofic-500
LOCATE FOR Codofic<0
IF FOUND()
   MESSAGEBOX("Oficina Menor a 0",16,"")
   BROWSE 
ENDIF 
*----------*
SELECT 2010  &&USE OFICINA EXCLUSIVE
ZAP
APPEND FROM OFICINA_BDO
*----------*
SELECT 4010  &&USE ACTUAL EXCLUSIVE
GO top
EntidadE=Entidad
UnidadE=Unidad
SELECT 2010  &&USE OFICINA EXCLUSIVE
REPLACE ALL Entidad    WITH EntidadE
REPLACE ALL Unidad     WITH UnidadE
REPLACE ALL Api_Estado WITH 1
*----------*
CLOSE DATABASES
*----------*